# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

volumes:
  order-db-data:

x-app-volume: &app-volume
  type: bind
  source: ./
  target: /github.com/go-feast/resty-backend

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  order-server:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - <<: *app-volume
    command:
      - "/go/bin/CompileDaemon"
      - "-log-prefix=false"
      - "-graceful-timeout=10"
      - "-graceful-kill=true"
      - "-exclude-dir=.git"
      - "-build=task PROJECT=order build-api-server"
      - "-command=/bin/server"
    environment:
      ADDR: order-server:8080
      DB: postgres://postgres:secret@postgres-order:5432/order
    ports:
      - "8080:8080"
    depends_on:
      postgres-order:
        condition: service_healthy

  postgres-order:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5