ARG BUILD_TARGET
ARG BUILD_PROJECT
ARG SERVICE_PORT
ARG METRIC_PORT
FROM golang:1.23 AS base

ARG BUILD_TARGET
ARG BUILD_PROJECT

WORKDIR /src

COPY go.mod .
COPY go.sum .

COPY . .

RUN CGO_ENABLED=0 go build -o /bin/app /src/cmd/$BUILD_PROJECT/$BUILD_TARGET/main.go

FROM alpine:latest as binary

ARG SERVICE_PORT
ARG METRIC_PORT

EXPOSE $SERVICE_PORT
EXPOSE $METRIC_PORT

COPY --from=base /bin/app /bin/

ENTRYPOINT ["/bin/app"]