# https://taskfile.dev

version: '3'

vars:
  OK_COLOR: '\033[32;01m'
  NO_COLOR: '\033[0m'
  LOCAL_DOCKER_COMPOSE: compose.yaml
  INTEGRATION_DOCKER_COMPOSE: ./testing/integration/docker-compose.yml

tasks:
  help:
    desc: Show the list of commands
    cmds:
      - task --list-all

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run -c .golangci.yml

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  test:
    #deps:
      #- set-up-integration-testing
    desc: Run tests
    cmds:
      - go test -gcflags=-l -covermode=atomic -race ./...
    env:
      ENVIRONMENT: testing

  build-api-server:
    desc: Build service
    envs:
      PROJECT: none
    cmds:
      - go build -buildvcs=false -ldflags="-s -w" -o /bin/server ./cmd/{{.PROJECT}}/server/*.go
    env:
      CGO_ENABLED: 0
      GOOS: linux

  build-api-consumer:
    desc: Build service
    cmds:
      - go build -buildvcs=false -ldflags="-s -w" -o bin/consumer ./cmd/consumer/main.go
    env:
      CGO_ENABLED: 0
      GOOS: linux

  local-build:
    desc: Docker compose up prometheus with our app
    cmds:
      - docker compose -f {{.LOCAL_DOCKER_COMPOSE}} -p resty build
      - task local-up

  local-up:
    desc: Docker compose up prometheus with our app
    cmds:
      - docker compose -f {{.LOCAL_DOCKER_COMPOSE}} -p resty up -d


  local-down:
    desc: Docker compose down prometheus with our app
    cmds:
      - docker compose -f {{.LOCAL_DOCKER_COMPOSE}} -p resty down

  set-up-integration-testing:
    desc: Set-up of Kafka, Redis, Postgres and others for integration testing
    cmds:
      - docker compose -f {{.INTEGRATION_DOCKER_COMPOSE}} up -d

  clean-up-after-integration-testing:
    desc: Clean up Kafka, Redis, Postgres and others after integration testing
    cmds:
      - docker compose -f {{.INTEGRATION_DOCKER_COMPOSE}} down
  default:
    cmds:
      - task: help
