global:

alerting:

rule_files:

scrape_configs:
  - job_name: order-service
    scrape_interval: 1m
    static_configs:
      # metric port. app - represents host+port. In docker-compose our service labeled as "app".
      - targets: ["service:8081"]
      - targets: ["service-consumer:8082"]